[project]
name = "resume-critiquer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sidhartha2002", email = "mohantysidhartha2002@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.24.0",
    "pydantic>=2.13.5",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
    "streamlit>=1.64.0",
]

[project.scripts]
resume-critiquer = "resume_critiquer:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
